name: Enviar E-mail Diariamente

on:
  workflow_dispatch
 # schedule:
  # - cron:  '0 * * * *'
jobs:
  import-data:
    runs-on: macos-latest
    environment: my_env
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("yfR")'
          R -e 'install.packages("rugarch")'
          R -e 'install.packages("gmailr")'

      - name: Run R script
        run: Rscript R/escreve_csv.R

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add *
          git commit -am "GH ACTION Headlines $(date)"
          git pull origin master
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions


      - name: Enviar e-mail
        working-directory: .github/workflows
        env:
          MEU_EMAIL: ${{ secrets.MEU_EMAIL }}
          SEU_EMAIL: ${{ secrets.SEU_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          Rscript -e 'library(gmailr);
                      meu_email <- Sys.getenv("MEU_EMAIL");
                      seu_email <- Sys.getenv("SEU_EMAIL");
                      CLIENT_ID <- Sys.getenv("CLIENT_ID");
                      CLIENT_SECRET <- Sys.getenv("CLIENT_SECRET");
                      options(
                        gargle_oauth_cache = ".secret",
                        gargle_oauth_email = meu_email
                      );
                      gm_auth_configure(key = CLIENT_ID, secret = CLIENT_SECRET);
                      gm_auth(email = meu_email);
                      dados <- read.csv("../../dados/previsao.csv");
                      dados[1, 1] <- dados[1, 1] + 1;
                      write.csv(dados, file = "dados/previsao.csv", row.names = FALSE);
                      mensagem <- "Teste";
                      arquivo <- file.path("dados/previsao.csv");
                      msg <- gm_mime() |> gm_from(meu_email) |>
                             gm_to(seu_email) |> gm_text_body(mensagem) |>
                             gm_attach_file(arquivo);
                      gm_send_message(msg);'
        
